spring:
  application:
    name: customer-api
  datasource:
    username: secret
    password: secret
    url: jdbc:postgresql://localhost:5434/customer-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: 9092
    consumer:
      group-id: customer-api
server:
  port: 8089
