version: '3.1'

services:
  customer-api:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: secret
      POSTGRES_DB: customer-api